import "./globals.scss";

import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { theme } from "@root/theme.config";
import { Inter } from "next/font/google";
import Head from "next/head";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import NextAuthSessionProviders from "../components/next-auth/provider";

export const metadata: Metadata = {
  title: "Palma",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider theme={theme}>
            <NextAuthSessionProviders>{children}</NextAuthSessionProviders>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
