import '@styles/globals.scss';

import { ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import { theme } from '@root/theme.config';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import NextAuthSessionProviders from '../components/next-auth/provider';
import { ServiceProvider } from '../context/service/context';

export const metadata: Metadata = {
  title: 'Palma',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider theme={theme}>
            <ServiceProvider>
              <NextAuthSessionProviders>{children}</NextAuthSessionProviders>
            </ServiceProvider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
